/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: balancebot.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "balancebot.pb-c.h"
void   balance_bot_protobuf__pitch_pid__init
                     (BalanceBotProtobuf__PitchPID         *message)
{
  static const BalanceBotProtobuf__PitchPID init_value = BALANCE_BOT_PROTOBUF__PITCH_PID__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__pitch_pid__get_packed_size
                     (const BalanceBotProtobuf__PitchPID *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__pitch_pid__pack
                     (const BalanceBotProtobuf__PitchPID *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__pitch_pid__pack_to_buffer
                     (const BalanceBotProtobuf__PitchPID *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__PitchPID *
       balance_bot_protobuf__pitch_pid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__PitchPID *)
     protobuf_c_message_unpack (&balance_bot_protobuf__pitch_pid__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__pitch_pid__free_unpacked
                     (BalanceBotProtobuf__PitchPID *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__pitch_pidstate__init
                     (BalanceBotProtobuf__PitchPIDState         *message)
{
  static const BalanceBotProtobuf__PitchPIDState init_value = BALANCE_BOT_PROTOBUF__PITCH_PIDSTATE__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__pitch_pidstate__get_packed_size
                     (const BalanceBotProtobuf__PitchPIDState *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pidstate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__pitch_pidstate__pack
                     (const BalanceBotProtobuf__PitchPIDState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pidstate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__pitch_pidstate__pack_to_buffer
                     (const BalanceBotProtobuf__PitchPIDState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pidstate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__PitchPIDState *
       balance_bot_protobuf__pitch_pidstate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__PitchPIDState *)
     protobuf_c_message_unpack (&balance_bot_protobuf__pitch_pidstate__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__pitch_pidstate__free_unpacked
                     (BalanceBotProtobuf__PitchPIDState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_pidstate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__pitch_controller__init
                     (BalanceBotProtobuf__PitchController         *message)
{
  static const BalanceBotProtobuf__PitchController init_value = BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__pitch_controller__get_packed_size
                     (const BalanceBotProtobuf__PitchController *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__pitch_controller__pack
                     (const BalanceBotProtobuf__PitchController *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__pitch_controller__pack_to_buffer
                     (const BalanceBotProtobuf__PitchController *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__PitchController *
       balance_bot_protobuf__pitch_controller__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__PitchController *)
     protobuf_c_message_unpack (&balance_bot_protobuf__pitch_controller__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__pitch_controller__free_unpacked
                     (BalanceBotProtobuf__PitchController *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__pitch_controller_state__init
                     (BalanceBotProtobuf__PitchControllerState         *message)
{
  static const BalanceBotProtobuf__PitchControllerState init_value = BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_STATE__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__pitch_controller_state__get_packed_size
                     (const BalanceBotProtobuf__PitchControllerState *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__pitch_controller_state__pack
                     (const BalanceBotProtobuf__PitchControllerState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__pitch_controller_state__pack_to_buffer
                     (const BalanceBotProtobuf__PitchControllerState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__PitchControllerState *
       balance_bot_protobuf__pitch_controller_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__PitchControllerState *)
     protobuf_c_message_unpack (&balance_bot_protobuf__pitch_controller_state__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__pitch_controller_state__free_unpacked
                     (BalanceBotProtobuf__PitchControllerState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__pitch_controller_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__yaw_pid__init
                     (BalanceBotProtobuf__YawPID         *message)
{
  static const BalanceBotProtobuf__YawPID init_value = BALANCE_BOT_PROTOBUF__YAW_PID__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__yaw_pid__get_packed_size
                     (const BalanceBotProtobuf__YawPID *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__yaw_pid__pack
                     (const BalanceBotProtobuf__YawPID *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__yaw_pid__pack_to_buffer
                     (const BalanceBotProtobuf__YawPID *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__YawPID *
       balance_bot_protobuf__yaw_pid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__YawPID *)
     protobuf_c_message_unpack (&balance_bot_protobuf__yaw_pid__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__yaw_pid__free_unpacked
                     (BalanceBotProtobuf__YawPID *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__yaw_pidstate__init
                     (BalanceBotProtobuf__YawPIDState         *message)
{
  static const BalanceBotProtobuf__YawPIDState init_value = BALANCE_BOT_PROTOBUF__YAW_PIDSTATE__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__yaw_pidstate__get_packed_size
                     (const BalanceBotProtobuf__YawPIDState *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pidstate__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__yaw_pidstate__pack
                     (const BalanceBotProtobuf__YawPIDState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pidstate__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__yaw_pidstate__pack_to_buffer
                     (const BalanceBotProtobuf__YawPIDState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pidstate__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__YawPIDState *
       balance_bot_protobuf__yaw_pidstate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__YawPIDState *)
     protobuf_c_message_unpack (&balance_bot_protobuf__yaw_pidstate__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__yaw_pidstate__free_unpacked
                     (BalanceBotProtobuf__YawPIDState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_pidstate__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__yaw_controller__init
                     (BalanceBotProtobuf__YawController         *message)
{
  static const BalanceBotProtobuf__YawController init_value = BALANCE_BOT_PROTOBUF__YAW_CONTROLLER__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__yaw_controller__get_packed_size
                     (const BalanceBotProtobuf__YawController *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__yaw_controller__pack
                     (const BalanceBotProtobuf__YawController *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__yaw_controller__pack_to_buffer
                     (const BalanceBotProtobuf__YawController *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__YawController *
       balance_bot_protobuf__yaw_controller__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__YawController *)
     protobuf_c_message_unpack (&balance_bot_protobuf__yaw_controller__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__yaw_controller__free_unpacked
                     (BalanceBotProtobuf__YawController *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__yaw_controller_state__init
                     (BalanceBotProtobuf__YawControllerState         *message)
{
  static const BalanceBotProtobuf__YawControllerState init_value = BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_STATE__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__yaw_controller_state__get_packed_size
                     (const BalanceBotProtobuf__YawControllerState *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__yaw_controller_state__pack
                     (const BalanceBotProtobuf__YawControllerState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__yaw_controller_state__pack_to_buffer
                     (const BalanceBotProtobuf__YawControllerState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__YawControllerState *
       balance_bot_protobuf__yaw_controller_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__YawControllerState *)
     protobuf_c_message_unpack (&balance_bot_protobuf__yaw_controller_state__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__yaw_controller_state__free_unpacked
                     (BalanceBotProtobuf__YawControllerState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__yaw_controller_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__physical_characteristics__init
                     (BalanceBotProtobuf__PhysicalCharacteristics         *message)
{
  static const BalanceBotProtobuf__PhysicalCharacteristics init_value = BALANCE_BOT_PROTOBUF__PHYSICAL_CHARACTERISTICS__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__physical_characteristics__get_packed_size
                     (const BalanceBotProtobuf__PhysicalCharacteristics *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__physical_characteristics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__physical_characteristics__pack
                     (const BalanceBotProtobuf__PhysicalCharacteristics *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__physical_characteristics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__physical_characteristics__pack_to_buffer
                     (const BalanceBotProtobuf__PhysicalCharacteristics *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__physical_characteristics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__PhysicalCharacteristics *
       balance_bot_protobuf__physical_characteristics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__PhysicalCharacteristics *)
     protobuf_c_message_unpack (&balance_bot_protobuf__physical_characteristics__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__physical_characteristics__free_unpacked
                     (BalanceBotProtobuf__PhysicalCharacteristics *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__physical_characteristics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__motor_config__init
                     (BalanceBotProtobuf__MotorConfig         *message)
{
  static const BalanceBotProtobuf__MotorConfig init_value = BALANCE_BOT_PROTOBUF__MOTOR_CONFIG__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__motor_config__get_packed_size
                     (const BalanceBotProtobuf__MotorConfig *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__motor_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__motor_config__pack
                     (const BalanceBotProtobuf__MotorConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__motor_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__motor_config__pack_to_buffer
                     (const BalanceBotProtobuf__MotorConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__motor_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__MotorConfig *
       balance_bot_protobuf__motor_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__MotorConfig *)
     protobuf_c_message_unpack (&balance_bot_protobuf__motor_config__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__motor_config__free_unpacked
                     (BalanceBotProtobuf__MotorConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__motor_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__drive__init
                     (BalanceBotProtobuf__Drive         *message)
{
  static const BalanceBotProtobuf__Drive init_value = BALANCE_BOT_PROTOBUF__DRIVE__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__drive__get_packed_size
                     (const BalanceBotProtobuf__Drive *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__drive__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__drive__pack
                     (const BalanceBotProtobuf__Drive *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__drive__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__drive__pack_to_buffer
                     (const BalanceBotProtobuf__Drive *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__drive__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__Drive *
       balance_bot_protobuf__drive__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__Drive *)
     protobuf_c_message_unpack (&balance_bot_protobuf__drive__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__drive__free_unpacked
                     (BalanceBotProtobuf__Drive *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__drive__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__web2_bot__init
                     (BalanceBotProtobuf__Web2Bot         *message)
{
  static const BalanceBotProtobuf__Web2Bot init_value = BALANCE_BOT_PROTOBUF__WEB2_BOT__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__web2_bot__get_packed_size
                     (const BalanceBotProtobuf__Web2Bot *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__web2_bot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__web2_bot__pack
                     (const BalanceBotProtobuf__Web2Bot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__web2_bot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__web2_bot__pack_to_buffer
                     (const BalanceBotProtobuf__Web2Bot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__web2_bot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__Web2Bot *
       balance_bot_protobuf__web2_bot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__Web2Bot *)
     protobuf_c_message_unpack (&balance_bot_protobuf__web2_bot__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__web2_bot__free_unpacked
                     (BalanceBotProtobuf__Web2Bot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__web2_bot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__motor_state__init
                     (BalanceBotProtobuf__MotorState         *message)
{
  static const BalanceBotProtobuf__MotorState init_value = BALANCE_BOT_PROTOBUF__MOTOR_STATE__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__motor_state__get_packed_size
                     (const BalanceBotProtobuf__MotorState *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__motor_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__motor_state__pack
                     (const BalanceBotProtobuf__MotorState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__motor_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__motor_state__pack_to_buffer
                     (const BalanceBotProtobuf__MotorState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__motor_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__MotorState *
       balance_bot_protobuf__motor_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__MotorState *)
     protobuf_c_message_unpack (&balance_bot_protobuf__motor_state__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__motor_state__free_unpacked
                     (BalanceBotProtobuf__MotorState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__motor_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__robot_state__init
                     (BalanceBotProtobuf__RobotState         *message)
{
  static const BalanceBotProtobuf__RobotState init_value = BALANCE_BOT_PROTOBUF__ROBOT_STATE__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__robot_state__get_packed_size
                     (const BalanceBotProtobuf__RobotState *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__robot_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__robot_state__pack
                     (const BalanceBotProtobuf__RobotState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__robot_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__robot_state__pack_to_buffer
                     (const BalanceBotProtobuf__RobotState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__robot_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__RobotState *
       balance_bot_protobuf__robot_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__RobotState *)
     protobuf_c_message_unpack (&balance_bot_protobuf__robot_state__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__robot_state__free_unpacked
                     (BalanceBotProtobuf__RobotState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__robot_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   balance_bot_protobuf__bot2_web__init
                     (BalanceBotProtobuf__Bot2Web         *message)
{
  static const BalanceBotProtobuf__Bot2Web init_value = BALANCE_BOT_PROTOBUF__BOT2_WEB__INIT;
  *message = init_value;
}
size_t balance_bot_protobuf__bot2_web__get_packed_size
                     (const BalanceBotProtobuf__Bot2Web *message)
{
  assert(message->base.descriptor == &balance_bot_protobuf__bot2_web__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t balance_bot_protobuf__bot2_web__pack
                     (const BalanceBotProtobuf__Bot2Web *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &balance_bot_protobuf__bot2_web__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t balance_bot_protobuf__bot2_web__pack_to_buffer
                     (const BalanceBotProtobuf__Bot2Web *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &balance_bot_protobuf__bot2_web__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BalanceBotProtobuf__Bot2Web *
       balance_bot_protobuf__bot2_web__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BalanceBotProtobuf__Bot2Web *)
     protobuf_c_message_unpack (&balance_bot_protobuf__bot2_web__descriptor,
                                allocator, len, data);
}
void   balance_bot_protobuf__bot2_web__free_unpacked
                     (BalanceBotProtobuf__Bot2Web *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &balance_bot_protobuf__bot2_web__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor balance_bot_protobuf__pitch_pid__field_descriptors[7] =
{
  {
    "kp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPID, kp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ki",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPID, ki),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kd",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPID, kd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integral_zero_threshold",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPID, integral_zero_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integral_saturation_limit",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPID, integral_saturation_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reset_integral",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPID, reset_integral),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_gravity",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPID, add_gravity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__pitch_pid__field_indices_by_name[] = {
  6,   /* field[6] = add_gravity */
  4,   /* field[4] = integral_saturation_limit */
  3,   /* field[3] = integral_zero_threshold */
  2,   /* field[2] = kd */
  1,   /* field[1] = ki */
  0,   /* field[0] = kp */
  5,   /* field[5] = reset_integral */
};
static const ProtobufCIntRange balance_bot_protobuf__pitch_pid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_pid__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.PitchPID",
  "PitchPID",
  "BalanceBotProtobuf__PitchPID",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__PitchPID),
  7,
  balance_bot_protobuf__pitch_pid__field_descriptors,
  balance_bot_protobuf__pitch_pid__field_indices_by_name,
  1,  balance_bot_protobuf__pitch_pid__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__pitch_pid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__pitch_pidstate__field_descriptors[5] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPIDState, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integral",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPIDState, integral),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derivative",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPIDState, derivative),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPIDState, output),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saturated",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchPIDState, saturated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__pitch_pidstate__field_indices_by_name[] = {
  2,   /* field[2] = derivative */
  0,   /* field[0] = error */
  1,   /* field[1] = integral */
  3,   /* field[3] = output */
  4,   /* field[4] = saturated */
};
static const ProtobufCIntRange balance_bot_protobuf__pitch_pidstate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_pidstate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.PitchPIDState",
  "PitchPIDState",
  "BalanceBotProtobuf__PitchPIDState",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__PitchPIDState),
  5,
  balance_bot_protobuf__pitch_pidstate__field_descriptors,
  balance_bot_protobuf__pitch_pidstate__field_indices_by_name,
  1,  balance_bot_protobuf__pitch_pidstate__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__pitch_pidstate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__pitch_controller__field_descriptors[2] =
{
  {
    "active",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchController, active),
    &balance_bot_protobuf__pitch_controller_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PitchController, pid),
    &balance_bot_protobuf__pitch_pid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__pitch_controller__field_indices_by_name[] = {
  0,   /* field[0] = active */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange balance_bot_protobuf__pitch_controller__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_controller__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.PitchController",
  "PitchController",
  "BalanceBotProtobuf__PitchController",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__PitchController),
  2,
  balance_bot_protobuf__pitch_controller__field_descriptors,
  balance_bot_protobuf__pitch_controller__field_indices_by_name,
  1,  balance_bot_protobuf__pitch_controller__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__pitch_controller__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__pitch_controller_state__field_descriptors[1] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BalanceBotProtobuf__PitchControllerState, state_case),
    offsetof(BalanceBotProtobuf__PitchControllerState, pid),
    &balance_bot_protobuf__pitch_pidstate__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__pitch_controller_state__field_indices_by_name[] = {
  0,   /* field[0] = pid */
};
static const ProtobufCIntRange balance_bot_protobuf__pitch_controller_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_controller_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.PitchControllerState",
  "PitchControllerState",
  "BalanceBotProtobuf__PitchControllerState",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__PitchControllerState),
  1,
  balance_bot_protobuf__pitch_controller_state__field_descriptors,
  balance_bot_protobuf__pitch_controller_state__field_indices_by_name,
  1,  balance_bot_protobuf__pitch_controller_state__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__pitch_controller_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__yaw_pid__field_descriptors[6] =
{
  {
    "kp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPID, kp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ki",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPID, ki),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kd",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPID, kd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integral_zero_threshold",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPID, integral_zero_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integral_saturation_limit",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPID, integral_saturation_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reset_integral",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPID, reset_integral),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__yaw_pid__field_indices_by_name[] = {
  4,   /* field[4] = integral_saturation_limit */
  3,   /* field[3] = integral_zero_threshold */
  2,   /* field[2] = kd */
  1,   /* field[1] = ki */
  0,   /* field[0] = kp */
  5,   /* field[5] = reset_integral */
};
static const ProtobufCIntRange balance_bot_protobuf__yaw_pid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_pid__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.YawPID",
  "YawPID",
  "BalanceBotProtobuf__YawPID",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__YawPID),
  6,
  balance_bot_protobuf__yaw_pid__field_descriptors,
  balance_bot_protobuf__yaw_pid__field_indices_by_name,
  1,  balance_bot_protobuf__yaw_pid__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__yaw_pid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__yaw_pidstate__field_descriptors[5] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPIDState, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "integral",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPIDState, integral),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derivative",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPIDState, derivative),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPIDState, output),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saturated",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawPIDState, saturated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__yaw_pidstate__field_indices_by_name[] = {
  2,   /* field[2] = derivative */
  0,   /* field[0] = error */
  1,   /* field[1] = integral */
  3,   /* field[3] = output */
  4,   /* field[4] = saturated */
};
static const ProtobufCIntRange balance_bot_protobuf__yaw_pidstate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_pidstate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.YawPIDState",
  "YawPIDState",
  "BalanceBotProtobuf__YawPIDState",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__YawPIDState),
  5,
  balance_bot_protobuf__yaw_pidstate__field_descriptors,
  balance_bot_protobuf__yaw_pidstate__field_indices_by_name,
  1,  balance_bot_protobuf__yaw_pidstate__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__yaw_pidstate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__yaw_controller__field_descriptors[2] =
{
  {
    "active",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawController, active),
    &balance_bot_protobuf__yaw_controller_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__YawController, pid),
    &balance_bot_protobuf__yaw_pid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__yaw_controller__field_indices_by_name[] = {
  0,   /* field[0] = active */
  1,   /* field[1] = pid */
};
static const ProtobufCIntRange balance_bot_protobuf__yaw_controller__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_controller__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.YawController",
  "YawController",
  "BalanceBotProtobuf__YawController",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__YawController),
  2,
  balance_bot_protobuf__yaw_controller__field_descriptors,
  balance_bot_protobuf__yaw_controller__field_indices_by_name,
  1,  balance_bot_protobuf__yaw_controller__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__yaw_controller__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__yaw_controller_state__field_descriptors[1] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BalanceBotProtobuf__YawControllerState, state_case),
    offsetof(BalanceBotProtobuf__YawControllerState, pid),
    &balance_bot_protobuf__yaw_pidstate__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__yaw_controller_state__field_indices_by_name[] = {
  0,   /* field[0] = pid */
};
static const ProtobufCIntRange balance_bot_protobuf__yaw_controller_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_controller_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.YawControllerState",
  "YawControllerState",
  "BalanceBotProtobuf__YawControllerState",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__YawControllerState),
  1,
  balance_bot_protobuf__yaw_controller_state__field_descriptors,
  balance_bot_protobuf__yaw_controller_state__field_indices_by_name,
  1,  balance_bot_protobuf__yaw_controller_state__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__yaw_controller_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__physical_characteristics__field_descriptors[4] =
{
  {
    "wheel_radius",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PhysicalCharacteristics, wheel_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wheel_base",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PhysicalCharacteristics, wheel_base),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gravity_accel",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PhysicalCharacteristics, gravity_accel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "torque_length",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__PhysicalCharacteristics, torque_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__physical_characteristics__field_indices_by_name[] = {
  2,   /* field[2] = gravity_accel */
  3,   /* field[3] = torque_length */
  1,   /* field[1] = wheel_base */
  0,   /* field[0] = wheel_radius */
};
static const ProtobufCIntRange balance_bot_protobuf__physical_characteristics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__physical_characteristics__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.PhysicalCharacteristics",
  "PhysicalCharacteristics",
  "BalanceBotProtobuf__PhysicalCharacteristics",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__PhysicalCharacteristics),
  4,
  balance_bot_protobuf__physical_characteristics__field_descriptors,
  balance_bot_protobuf__physical_characteristics__field_indices_by_name,
  1,  balance_bot_protobuf__physical_characteristics__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__physical_characteristics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__motor_config__field_descriptors[6] =
{
  {
    "max_speed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorConfig, max_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "static_friction_neg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorConfig, static_friction_neg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "static_friction_pos",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorConfig, static_friction_pos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "static_friction_time",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorConfig, static_friction_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brake_time",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorConfig, brake_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lut",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BalanceBotProtobuf__MotorConfig, n_lut),
    offsetof(BalanceBotProtobuf__MotorConfig, lut),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__motor_config__field_indices_by_name[] = {
  4,   /* field[4] = brake_time */
  5,   /* field[5] = lut */
  0,   /* field[0] = max_speed */
  1,   /* field[1] = static_friction_neg */
  2,   /* field[2] = static_friction_pos */
  3,   /* field[3] = static_friction_time */
};
static const ProtobufCIntRange balance_bot_protobuf__motor_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__motor_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.MotorConfig",
  "MotorConfig",
  "BalanceBotProtobuf__MotorConfig",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__MotorConfig),
  6,
  balance_bot_protobuf__motor_config__field_descriptors,
  balance_bot_protobuf__motor_config__field_indices_by_name,
  1,  balance_bot_protobuf__motor_config__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__motor_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__drive__field_descriptors[2] =
{
  {
    "linear",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Drive, linear),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angular",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Drive, angular),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__drive__field_indices_by_name[] = {
  1,   /* field[1] = angular */
  0,   /* field[0] = linear */
};
static const ProtobufCIntRange balance_bot_protobuf__drive__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__drive__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.Drive",
  "Drive",
  "BalanceBotProtobuf__Drive",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__Drive),
  2,
  balance_bot_protobuf__drive__field_descriptors,
  balance_bot_protobuf__drive__field_indices_by_name,
  1,  balance_bot_protobuf__drive__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__drive__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__web2_bot__field_descriptors[32] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_enable_balancing",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, write_enable_balancing),
    &balance_bot_protobuf__optional_bool__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_pitch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, write_pitch),
    &balance_bot_protobuf__pitch_controller__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_yaw",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, write_yaw),
    &balance_bot_protobuf__yaw_controller__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_physical",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, write_physical),
    &balance_bot_protobuf__physical_characteristics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_motor_l",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, write_motor_l),
    &balance_bot_protobuf__motor_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "write_motor_r",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, write_motor_r),
    &balance_bot_protobuf__motor_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_enable_balancing",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, save_enable_balancing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_pitch",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, save_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_yaw",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, save_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_physical",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, save_physical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_motor_l",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, save_motor_l),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "save_motor_r",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, save_motor_r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_curr_enable_balancing",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_curr_enable_balancing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_curr_pitch",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_curr_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_curr_yaw",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_curr_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_curr_physical",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_curr_physical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_curr_motor_l",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_curr_motor_l),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_curr_motor_r",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_curr_motor_r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_saved_enable_balancing",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_saved_enable_balancing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_saved_pitch",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_saved_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_saved_yaw",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_saved_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_saved_physical",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_saved_physical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_saved_motor_l",
    24,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_saved_motor_l),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "read_saved_motor_r",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, read_saved_motor_r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_enable_balancing",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, load_enable_balancing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_pitch",
    27,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, load_pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_yaw",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, load_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_physical",
    29,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, load_physical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_motor_l",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, load_motor_l),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_motor_r",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, load_motor_r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drive",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Web2Bot, drive),
    &balance_bot_protobuf__drive__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__web2_bot__field_indices_by_name[] = {
  31,   /* field[31] = drive */
  0,   /* field[0] = id */
  25,   /* field[25] = load_enable_balancing */
  29,   /* field[29] = load_motor_l */
  30,   /* field[30] = load_motor_r */
  28,   /* field[28] = load_physical */
  26,   /* field[26] = load_pitch */
  27,   /* field[27] = load_yaw */
  13,   /* field[13] = read_curr_enable_balancing */
  17,   /* field[17] = read_curr_motor_l */
  18,   /* field[18] = read_curr_motor_r */
  16,   /* field[16] = read_curr_physical */
  14,   /* field[14] = read_curr_pitch */
  15,   /* field[15] = read_curr_yaw */
  19,   /* field[19] = read_saved_enable_balancing */
  23,   /* field[23] = read_saved_motor_l */
  24,   /* field[24] = read_saved_motor_r */
  22,   /* field[22] = read_saved_physical */
  20,   /* field[20] = read_saved_pitch */
  21,   /* field[21] = read_saved_yaw */
  7,   /* field[7] = save_enable_balancing */
  11,   /* field[11] = save_motor_l */
  12,   /* field[12] = save_motor_r */
  10,   /* field[10] = save_physical */
  8,   /* field[8] = save_pitch */
  9,   /* field[9] = save_yaw */
  1,   /* field[1] = write_enable_balancing */
  5,   /* field[5] = write_motor_l */
  6,   /* field[6] = write_motor_r */
  4,   /* field[4] = write_physical */
  2,   /* field[2] = write_pitch */
  3,   /* field[3] = write_yaw */
};
static const ProtobufCIntRange balance_bot_protobuf__web2_bot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 32 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__web2_bot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.Web2Bot",
  "Web2Bot",
  "BalanceBotProtobuf__Web2Bot",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__Web2Bot),
  32,
  balance_bot_protobuf__web2_bot__field_descriptors,
  balance_bot_protobuf__web2_bot__field_indices_by_name,
  1,  balance_bot_protobuf__web2_bot__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__web2_bot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__motor_state__field_descriptors[3] =
{
  {
    "angle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorState, angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "measured_speed",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorState, measured_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_speed",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__MotorState, cmd_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__motor_state__field_indices_by_name[] = {
  0,   /* field[0] = angle */
  2,   /* field[2] = cmd_speed */
  1,   /* field[1] = measured_speed */
};
static const ProtobufCIntRange balance_bot_protobuf__motor_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__motor_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.MotorState",
  "MotorState",
  "BalanceBotProtobuf__MotorState",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__MotorState),
  3,
  balance_bot_protobuf__motor_state__field_descriptors,
  balance_bot_protobuf__motor_state__field_indices_by_name,
  1,  balance_bot_protobuf__motor_state__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__motor_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__robot_state__field_descriptors[8] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left_motor",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, left_motor),
    &balance_bot_protobuf__motor_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right_motor",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, right_motor),
    &balance_bot_protobuf__motor_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch_state",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, pitch_state),
    &balance_bot_protobuf__pitch_controller_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw_state",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, yaw_state),
    &balance_bot_protobuf__yaw_controller_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dist_travelled",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__RobotState, dist_travelled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__robot_state__field_indices_by_name[] = {
  7,   /* field[7] = dist_travelled */
  3,   /* field[3] = left_motor */
  1,   /* field[1] = pitch */
  5,   /* field[5] = pitch_state */
  4,   /* field[4] = right_motor */
  0,   /* field[0] = timestamp */
  2,   /* field[2] = yaw */
  6,   /* field[6] = yaw_state */
};
static const ProtobufCIntRange balance_bot_protobuf__robot_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__robot_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.RobotState",
  "RobotState",
  "BalanceBotProtobuf__RobotState",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__RobotState),
  8,
  balance_bot_protobuf__robot_state__field_descriptors,
  balance_bot_protobuf__robot_state__field_indices_by_name,
  1,  balance_bot_protobuf__robot_state__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__robot_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor balance_bot_protobuf__bot2_web__field_descriptors[15] =
{
  {
    "ack",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, ack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curr_enable_balancing",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, curr_enable_balancing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curr_pitch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, curr_pitch),
    &balance_bot_protobuf__pitch_controller__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curr_yaw",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, curr_yaw),
    &balance_bot_protobuf__yaw_controller__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curr_physical",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, curr_physical),
    &balance_bot_protobuf__physical_characteristics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curr_motor_l",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, curr_motor_l),
    &balance_bot_protobuf__motor_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curr_motor_r",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, curr_motor_r),
    &balance_bot_protobuf__motor_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saved_enable_balancing",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, saved_enable_balancing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saved_pitch",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, saved_pitch),
    &balance_bot_protobuf__pitch_controller__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saved_yaw",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, saved_yaw),
    &balance_bot_protobuf__yaw_controller__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saved_physical",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, saved_physical),
    &balance_bot_protobuf__physical_characteristics__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saved_motor_l",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, saved_motor_l),
    &balance_bot_protobuf__motor_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saved_motor_r",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, saved_motor_r),
    &balance_bot_protobuf__motor_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "robot_state",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, robot_state),
    &balance_bot_protobuf__robot_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BalanceBotProtobuf__Bot2Web, log),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned balance_bot_protobuf__bot2_web__field_indices_by_name[] = {
  0,   /* field[0] = ack */
  1,   /* field[1] = curr_enable_balancing */
  5,   /* field[5] = curr_motor_l */
  6,   /* field[6] = curr_motor_r */
  4,   /* field[4] = curr_physical */
  2,   /* field[2] = curr_pitch */
  3,   /* field[3] = curr_yaw */
  14,   /* field[14] = log */
  13,   /* field[13] = robot_state */
  7,   /* field[7] = saved_enable_balancing */
  11,   /* field[11] = saved_motor_l */
  12,   /* field[12] = saved_motor_r */
  10,   /* field[10] = saved_physical */
  8,   /* field[8] = saved_pitch */
  9,   /* field[9] = saved_yaw */
};
static const ProtobufCIntRange balance_bot_protobuf__bot2_web__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor balance_bot_protobuf__bot2_web__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.Bot2Web",
  "Bot2Web",
  "BalanceBotProtobuf__Bot2Web",
  "BalanceBotProtobuf",
  sizeof(BalanceBotProtobuf__Bot2Web),
  15,
  balance_bot_protobuf__bot2_web__field_descriptors,
  balance_bot_protobuf__bot2_web__field_indices_by_name,
  1,  balance_bot_protobuf__bot2_web__number_ranges,
  (ProtobufCMessageInit) balance_bot_protobuf__bot2_web__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue balance_bot_protobuf__pitch_controller_type__enum_values_by_number[1] =
{
  { "PITCH_PID", "BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_TYPE__PITCH_PID", 0 },
};
static const ProtobufCIntRange balance_bot_protobuf__pitch_controller_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex balance_bot_protobuf__pitch_controller_type__enum_values_by_name[1] =
{
  { "PITCH_PID", 0 },
};
const ProtobufCEnumDescriptor balance_bot_protobuf__pitch_controller_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.PitchControllerType",
  "PitchControllerType",
  "BalanceBotProtobuf__PitchControllerType",
  "BalanceBotProtobuf",
  1,
  balance_bot_protobuf__pitch_controller_type__enum_values_by_number,
  1,
  balance_bot_protobuf__pitch_controller_type__enum_values_by_name,
  1,
  balance_bot_protobuf__pitch_controller_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue balance_bot_protobuf__yaw_controller_type__enum_values_by_number[1] =
{
  { "YAW_PID", "BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_TYPE__YAW_PID", 0 },
};
static const ProtobufCIntRange balance_bot_protobuf__yaw_controller_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex balance_bot_protobuf__yaw_controller_type__enum_values_by_name[1] =
{
  { "YAW_PID", 0 },
};
const ProtobufCEnumDescriptor balance_bot_protobuf__yaw_controller_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.YawControllerType",
  "YawControllerType",
  "BalanceBotProtobuf__YawControllerType",
  "BalanceBotProtobuf",
  1,
  balance_bot_protobuf__yaw_controller_type__enum_values_by_number,
  1,
  balance_bot_protobuf__yaw_controller_type__enum_values_by_name,
  1,
  balance_bot_protobuf__yaw_controller_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue balance_bot_protobuf__optional_bool__enum_values_by_number[3] =
{
  { "BOOL_FALSE", "BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL__BOOL_FALSE", 0 },
  { "BOOL_TRUE", "BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL__BOOL_TRUE", 1 },
  { "BOOL_UNSET", "BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL__BOOL_UNSET", 2 },
};
static const ProtobufCIntRange balance_bot_protobuf__optional_bool__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex balance_bot_protobuf__optional_bool__enum_values_by_name[3] =
{
  { "BOOL_FALSE", 0 },
  { "BOOL_TRUE", 1 },
  { "BOOL_UNSET", 2 },
};
const ProtobufCEnumDescriptor balance_bot_protobuf__optional_bool__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "BalanceBotProtobuf.OptionalBool",
  "OptionalBool",
  "BalanceBotProtobuf__OptionalBool",
  "BalanceBotProtobuf",
  3,
  balance_bot_protobuf__optional_bool__enum_values_by_number,
  3,
  balance_bot_protobuf__optional_bool__enum_values_by_name,
  1,
  balance_bot_protobuf__optional_bool__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
