/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: balancebot.proto */

#ifndef PROTOBUF_C_balancebot_2eproto__INCLUDED
#define PROTOBUF_C_balancebot_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _BalanceBotProtobuf__PitchPID BalanceBotProtobuf__PitchPID;
typedef struct _BalanceBotProtobuf__PitchPIDState BalanceBotProtobuf__PitchPIDState;
typedef struct _BalanceBotProtobuf__PitchController BalanceBotProtobuf__PitchController;
typedef struct _BalanceBotProtobuf__PitchControllerState BalanceBotProtobuf__PitchControllerState;
typedef struct _BalanceBotProtobuf__YawPID BalanceBotProtobuf__YawPID;
typedef struct _BalanceBotProtobuf__YawPIDState BalanceBotProtobuf__YawPIDState;
typedef struct _BalanceBotProtobuf__YawController BalanceBotProtobuf__YawController;
typedef struct _BalanceBotProtobuf__YawControllerState BalanceBotProtobuf__YawControllerState;
typedef struct _BalanceBotProtobuf__PhysicalCharacteristics BalanceBotProtobuf__PhysicalCharacteristics;
typedef struct _BalanceBotProtobuf__MotorConfig BalanceBotProtobuf__MotorConfig;
typedef struct _BalanceBotProtobuf__Drive BalanceBotProtobuf__Drive;
typedef struct _BalanceBotProtobuf__Web2Bot BalanceBotProtobuf__Web2Bot;
typedef struct _BalanceBotProtobuf__MotorState BalanceBotProtobuf__MotorState;
typedef struct _BalanceBotProtobuf__RobotState BalanceBotProtobuf__RobotState;
typedef struct _BalanceBotProtobuf__Bot2Web BalanceBotProtobuf__Bot2Web;


/* --- enums --- */

typedef enum _BalanceBotProtobuf__PitchControllerType {
  BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_TYPE__PITCH_PID = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_TYPE)
} BalanceBotProtobuf__PitchControllerType;
typedef enum _BalanceBotProtobuf__YawControllerType {
  BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_TYPE__YAW_PID = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_TYPE)
} BalanceBotProtobuf__YawControllerType;
typedef enum _BalanceBotProtobuf__OptionalBool {
  BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL__BOOL_FALSE = 0,
  BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL__BOOL_TRUE = 1,
  BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL__BOOL_UNSET = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL)
} BalanceBotProtobuf__OptionalBool;

/* --- messages --- */

struct  _BalanceBotProtobuf__PitchPID
{
  ProtobufCMessage base;
  float kp;
  float ki;
  float kd;
  float integral_zero_threshold;
  float integral_saturation_limit;
  protobuf_c_boolean reset_integral;
  protobuf_c_boolean add_gravity;
};
#define BALANCE_BOT_PROTOBUF__PITCH_PID__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__pitch_pid__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0 }


struct  _BalanceBotProtobuf__PitchPIDState
{
  ProtobufCMessage base;
  float error;
  float integral;
  float derivative;
  float output;
  float saturated;
};
#define BALANCE_BOT_PROTOBUF__PITCH_PIDSTATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__pitch_pidstate__descriptor) \
    , 0, 0, 0, 0, 0 }


struct  _BalanceBotProtobuf__PitchController
{
  ProtobufCMessage base;
  BalanceBotProtobuf__PitchControllerType active;
  BalanceBotProtobuf__PitchPID *pid;
};
#define BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__pitch_controller__descriptor) \
    , BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_TYPE__PITCH_PID, NULL }


typedef enum {
  BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_STATE__STATE__NOT_SET = 0,
  BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_STATE__STATE_PID = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_STATE__STATE)
} BalanceBotProtobuf__PitchControllerState__StateCase;

struct  _BalanceBotProtobuf__PitchControllerState
{
  ProtobufCMessage base;
  BalanceBotProtobuf__PitchControllerState__StateCase state_case;
  union {
    BalanceBotProtobuf__PitchPIDState *pid;
  };
};
#define BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__pitch_controller_state__descriptor) \
    , BALANCE_BOT_PROTOBUF__PITCH_CONTROLLER_STATE__STATE__NOT_SET, {0} }


struct  _BalanceBotProtobuf__YawPID
{
  ProtobufCMessage base;
  float kp;
  float ki;
  float kd;
  float integral_zero_threshold;
  float integral_saturation_limit;
  protobuf_c_boolean reset_integral;
};
#define BALANCE_BOT_PROTOBUF__YAW_PID__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__yaw_pid__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  _BalanceBotProtobuf__YawPIDState
{
  ProtobufCMessage base;
  float error;
  float integral;
  float derivative;
  float output;
  float saturated;
};
#define BALANCE_BOT_PROTOBUF__YAW_PIDSTATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__yaw_pidstate__descriptor) \
    , 0, 0, 0, 0, 0 }


struct  _BalanceBotProtobuf__YawController
{
  ProtobufCMessage base;
  BalanceBotProtobuf__YawControllerType active;
  BalanceBotProtobuf__YawPID *pid;
};
#define BALANCE_BOT_PROTOBUF__YAW_CONTROLLER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__yaw_controller__descriptor) \
    , BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_TYPE__YAW_PID, NULL }


typedef enum {
  BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_STATE__STATE__NOT_SET = 0,
  BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_STATE__STATE_PID = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_STATE__STATE)
} BalanceBotProtobuf__YawControllerState__StateCase;

struct  _BalanceBotProtobuf__YawControllerState
{
  ProtobufCMessage base;
  BalanceBotProtobuf__YawControllerState__StateCase state_case;
  union {
    BalanceBotProtobuf__YawPIDState *pid;
  };
};
#define BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__yaw_controller_state__descriptor) \
    , BALANCE_BOT_PROTOBUF__YAW_CONTROLLER_STATE__STATE__NOT_SET, {0} }


struct  _BalanceBotProtobuf__PhysicalCharacteristics
{
  ProtobufCMessage base;
  float wheel_radius;
  float wheel_base;
  float gravity_accel;
  float torque_length;
};
#define BALANCE_BOT_PROTOBUF__PHYSICAL_CHARACTERISTICS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__physical_characteristics__descriptor) \
    , 0, 0, 0, 0 }


struct  _BalanceBotProtobuf__MotorConfig
{
  ProtobufCMessage base;
  uint32_t max_speed;
  uint32_t static_friction_neg;
  uint32_t static_friction_pos;
  uint32_t static_friction_time;
  uint32_t brake_time;
  size_t n_lut;
  uint32_t *lut;
};
#define BALANCE_BOT_PROTOBUF__MOTOR_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__motor_config__descriptor) \
    , 0, 0, 0, 0, 0, 0,NULL }


struct  _BalanceBotProtobuf__Drive
{
  ProtobufCMessage base;
  float linear;
  float angular;
};
#define BALANCE_BOT_PROTOBUF__DRIVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__drive__descriptor) \
    , 0, 0 }


struct  _BalanceBotProtobuf__Web2Bot
{
  ProtobufCMessage base;
  uint32_t id;
  /*
   * Write data to temporary storage.
   */
  BalanceBotProtobuf__OptionalBool write_enable_balancing;
  BalanceBotProtobuf__PitchController *write_pitch;
  BalanceBotProtobuf__YawController *write_yaw;
  BalanceBotProtobuf__PhysicalCharacteristics *write_physical;
  BalanceBotProtobuf__MotorConfig *write_motor_l;
  BalanceBotProtobuf__MotorConfig *write_motor_r;
  /*
   * Save data to persistent storage.
   */
  protobuf_c_boolean save_enable_balancing;
  protobuf_c_boolean save_pitch;
  protobuf_c_boolean save_yaw;
  protobuf_c_boolean save_physical;
  protobuf_c_boolean save_motor_l;
  protobuf_c_boolean save_motor_r;
  /*
   * Read currently loaded data.
   */
  protobuf_c_boolean read_curr_enable_balancing;
  protobuf_c_boolean read_curr_pitch;
  protobuf_c_boolean read_curr_yaw;
  protobuf_c_boolean read_curr_physical;
  protobuf_c_boolean read_curr_motor_l;
  protobuf_c_boolean read_curr_motor_r;
  /*
   * Read saved data.
   */
  protobuf_c_boolean read_saved_enable_balancing;
  protobuf_c_boolean read_saved_pitch;
  protobuf_c_boolean read_saved_yaw;
  protobuf_c_boolean read_saved_physical;
  protobuf_c_boolean read_saved_motor_l;
  protobuf_c_boolean read_saved_motor_r;
  /*
   * Load saved data to current data.
   */
  protobuf_c_boolean load_enable_balancing;
  protobuf_c_boolean load_pitch;
  protobuf_c_boolean load_yaw;
  protobuf_c_boolean load_physical;
  protobuf_c_boolean load_motor_l;
  protobuf_c_boolean load_motor_r;
  /*
   * Drive the robot.
   */
  BalanceBotProtobuf__Drive *drive;
};
#define BALANCE_BOT_PROTOBUF__WEB2_BOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__web2_bot__descriptor) \
    , 0, BALANCE_BOT_PROTOBUF__OPTIONAL_BOOL__BOOL_FALSE, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL }


struct  _BalanceBotProtobuf__MotorState
{
  ProtobufCMessage base;
  float angle;
  float measured_speed;
  float cmd_speed;
};
#define BALANCE_BOT_PROTOBUF__MOTOR_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__motor_state__descriptor) \
    , 0, 0, 0 }


struct  _BalanceBotProtobuf__RobotState
{
  ProtobufCMessage base;
  int64_t timestamp;
  float pitch;
  float yaw;
  BalanceBotProtobuf__MotorState *left_motor;
  BalanceBotProtobuf__MotorState *right_motor;
  BalanceBotProtobuf__PitchControllerState *pitch_state;
  BalanceBotProtobuf__YawControllerState *yaw_state;
  float dist_travelled;
};
#define BALANCE_BOT_PROTOBUF__ROBOT_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__robot_state__descriptor) \
    , 0, 0, 0, NULL, NULL, NULL, NULL, 0 }


struct  _BalanceBotProtobuf__Bot2Web
{
  ProtobufCMessage base;
  /*
   * Acknowledge a message.
   */
  uint32_t ack;
  /*
   * Read currently loaded data.
   */
  ProtobufCBinaryData curr_enable_balancing;
  BalanceBotProtobuf__PitchController *curr_pitch;
  BalanceBotProtobuf__YawController *curr_yaw;
  BalanceBotProtobuf__PhysicalCharacteristics *curr_physical;
  BalanceBotProtobuf__MotorConfig *curr_motor_l;
  BalanceBotProtobuf__MotorConfig *curr_motor_r;
  /*
   * Read saved data.
   */
  ProtobufCBinaryData saved_enable_balancing;
  BalanceBotProtobuf__PitchController *saved_pitch;
  BalanceBotProtobuf__YawController *saved_yaw;
  BalanceBotProtobuf__PhysicalCharacteristics *saved_physical;
  BalanceBotProtobuf__MotorConfig *saved_motor_l;
  BalanceBotProtobuf__MotorConfig *saved_motor_r;
  /*
   * Robot state.
   */
  BalanceBotProtobuf__RobotState *robot_state;
  /*
   * Log message.
   */
  char *log;
};
#define BALANCE_BOT_PROTOBUF__BOT2_WEB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&balance_bot_protobuf__bot2_web__descriptor) \
    , 0, {0,NULL}, NULL, NULL, NULL, NULL, NULL, {0,NULL}, NULL, NULL, NULL, NULL, NULL, NULL, (char *)protobuf_c_empty_string }


/* BalanceBotProtobuf__PitchPID methods */
void   balance_bot_protobuf__pitch_pid__init
                     (BalanceBotProtobuf__PitchPID         *message);
size_t balance_bot_protobuf__pitch_pid__get_packed_size
                     (const BalanceBotProtobuf__PitchPID   *message);
size_t balance_bot_protobuf__pitch_pid__pack
                     (const BalanceBotProtobuf__PitchPID   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__pitch_pid__pack_to_buffer
                     (const BalanceBotProtobuf__PitchPID   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__PitchPID *
       balance_bot_protobuf__pitch_pid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__pitch_pid__free_unpacked
                     (BalanceBotProtobuf__PitchPID *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__PitchPIDState methods */
void   balance_bot_protobuf__pitch_pidstate__init
                     (BalanceBotProtobuf__PitchPIDState         *message);
size_t balance_bot_protobuf__pitch_pidstate__get_packed_size
                     (const BalanceBotProtobuf__PitchPIDState   *message);
size_t balance_bot_protobuf__pitch_pidstate__pack
                     (const BalanceBotProtobuf__PitchPIDState   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__pitch_pidstate__pack_to_buffer
                     (const BalanceBotProtobuf__PitchPIDState   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__PitchPIDState *
       balance_bot_protobuf__pitch_pidstate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__pitch_pidstate__free_unpacked
                     (BalanceBotProtobuf__PitchPIDState *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__PitchController methods */
void   balance_bot_protobuf__pitch_controller__init
                     (BalanceBotProtobuf__PitchController         *message);
size_t balance_bot_protobuf__pitch_controller__get_packed_size
                     (const BalanceBotProtobuf__PitchController   *message);
size_t balance_bot_protobuf__pitch_controller__pack
                     (const BalanceBotProtobuf__PitchController   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__pitch_controller__pack_to_buffer
                     (const BalanceBotProtobuf__PitchController   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__PitchController *
       balance_bot_protobuf__pitch_controller__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__pitch_controller__free_unpacked
                     (BalanceBotProtobuf__PitchController *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__PitchControllerState methods */
void   balance_bot_protobuf__pitch_controller_state__init
                     (BalanceBotProtobuf__PitchControllerState         *message);
size_t balance_bot_protobuf__pitch_controller_state__get_packed_size
                     (const BalanceBotProtobuf__PitchControllerState   *message);
size_t balance_bot_protobuf__pitch_controller_state__pack
                     (const BalanceBotProtobuf__PitchControllerState   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__pitch_controller_state__pack_to_buffer
                     (const BalanceBotProtobuf__PitchControllerState   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__PitchControllerState *
       balance_bot_protobuf__pitch_controller_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__pitch_controller_state__free_unpacked
                     (BalanceBotProtobuf__PitchControllerState *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__YawPID methods */
void   balance_bot_protobuf__yaw_pid__init
                     (BalanceBotProtobuf__YawPID         *message);
size_t balance_bot_protobuf__yaw_pid__get_packed_size
                     (const BalanceBotProtobuf__YawPID   *message);
size_t balance_bot_protobuf__yaw_pid__pack
                     (const BalanceBotProtobuf__YawPID   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__yaw_pid__pack_to_buffer
                     (const BalanceBotProtobuf__YawPID   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__YawPID *
       balance_bot_protobuf__yaw_pid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__yaw_pid__free_unpacked
                     (BalanceBotProtobuf__YawPID *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__YawPIDState methods */
void   balance_bot_protobuf__yaw_pidstate__init
                     (BalanceBotProtobuf__YawPIDState         *message);
size_t balance_bot_protobuf__yaw_pidstate__get_packed_size
                     (const BalanceBotProtobuf__YawPIDState   *message);
size_t balance_bot_protobuf__yaw_pidstate__pack
                     (const BalanceBotProtobuf__YawPIDState   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__yaw_pidstate__pack_to_buffer
                     (const BalanceBotProtobuf__YawPIDState   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__YawPIDState *
       balance_bot_protobuf__yaw_pidstate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__yaw_pidstate__free_unpacked
                     (BalanceBotProtobuf__YawPIDState *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__YawController methods */
void   balance_bot_protobuf__yaw_controller__init
                     (BalanceBotProtobuf__YawController         *message);
size_t balance_bot_protobuf__yaw_controller__get_packed_size
                     (const BalanceBotProtobuf__YawController   *message);
size_t balance_bot_protobuf__yaw_controller__pack
                     (const BalanceBotProtobuf__YawController   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__yaw_controller__pack_to_buffer
                     (const BalanceBotProtobuf__YawController   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__YawController *
       balance_bot_protobuf__yaw_controller__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__yaw_controller__free_unpacked
                     (BalanceBotProtobuf__YawController *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__YawControllerState methods */
void   balance_bot_protobuf__yaw_controller_state__init
                     (BalanceBotProtobuf__YawControllerState         *message);
size_t balance_bot_protobuf__yaw_controller_state__get_packed_size
                     (const BalanceBotProtobuf__YawControllerState   *message);
size_t balance_bot_protobuf__yaw_controller_state__pack
                     (const BalanceBotProtobuf__YawControllerState   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__yaw_controller_state__pack_to_buffer
                     (const BalanceBotProtobuf__YawControllerState   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__YawControllerState *
       balance_bot_protobuf__yaw_controller_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__yaw_controller_state__free_unpacked
                     (BalanceBotProtobuf__YawControllerState *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__PhysicalCharacteristics methods */
void   balance_bot_protobuf__physical_characteristics__init
                     (BalanceBotProtobuf__PhysicalCharacteristics         *message);
size_t balance_bot_protobuf__physical_characteristics__get_packed_size
                     (const BalanceBotProtobuf__PhysicalCharacteristics   *message);
size_t balance_bot_protobuf__physical_characteristics__pack
                     (const BalanceBotProtobuf__PhysicalCharacteristics   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__physical_characteristics__pack_to_buffer
                     (const BalanceBotProtobuf__PhysicalCharacteristics   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__PhysicalCharacteristics *
       balance_bot_protobuf__physical_characteristics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__physical_characteristics__free_unpacked
                     (BalanceBotProtobuf__PhysicalCharacteristics *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__MotorConfig methods */
void   balance_bot_protobuf__motor_config__init
                     (BalanceBotProtobuf__MotorConfig         *message);
size_t balance_bot_protobuf__motor_config__get_packed_size
                     (const BalanceBotProtobuf__MotorConfig   *message);
size_t balance_bot_protobuf__motor_config__pack
                     (const BalanceBotProtobuf__MotorConfig   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__motor_config__pack_to_buffer
                     (const BalanceBotProtobuf__MotorConfig   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__MotorConfig *
       balance_bot_protobuf__motor_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__motor_config__free_unpacked
                     (BalanceBotProtobuf__MotorConfig *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__Drive methods */
void   balance_bot_protobuf__drive__init
                     (BalanceBotProtobuf__Drive         *message);
size_t balance_bot_protobuf__drive__get_packed_size
                     (const BalanceBotProtobuf__Drive   *message);
size_t balance_bot_protobuf__drive__pack
                     (const BalanceBotProtobuf__Drive   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__drive__pack_to_buffer
                     (const BalanceBotProtobuf__Drive   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__Drive *
       balance_bot_protobuf__drive__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__drive__free_unpacked
                     (BalanceBotProtobuf__Drive *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__Web2Bot methods */
void   balance_bot_protobuf__web2_bot__init
                     (BalanceBotProtobuf__Web2Bot         *message);
size_t balance_bot_protobuf__web2_bot__get_packed_size
                     (const BalanceBotProtobuf__Web2Bot   *message);
size_t balance_bot_protobuf__web2_bot__pack
                     (const BalanceBotProtobuf__Web2Bot   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__web2_bot__pack_to_buffer
                     (const BalanceBotProtobuf__Web2Bot   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__Web2Bot *
       balance_bot_protobuf__web2_bot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__web2_bot__free_unpacked
                     (BalanceBotProtobuf__Web2Bot *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__MotorState methods */
void   balance_bot_protobuf__motor_state__init
                     (BalanceBotProtobuf__MotorState         *message);
size_t balance_bot_protobuf__motor_state__get_packed_size
                     (const BalanceBotProtobuf__MotorState   *message);
size_t balance_bot_protobuf__motor_state__pack
                     (const BalanceBotProtobuf__MotorState   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__motor_state__pack_to_buffer
                     (const BalanceBotProtobuf__MotorState   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__MotorState *
       balance_bot_protobuf__motor_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__motor_state__free_unpacked
                     (BalanceBotProtobuf__MotorState *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__RobotState methods */
void   balance_bot_protobuf__robot_state__init
                     (BalanceBotProtobuf__RobotState         *message);
size_t balance_bot_protobuf__robot_state__get_packed_size
                     (const BalanceBotProtobuf__RobotState   *message);
size_t balance_bot_protobuf__robot_state__pack
                     (const BalanceBotProtobuf__RobotState   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__robot_state__pack_to_buffer
                     (const BalanceBotProtobuf__RobotState   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__RobotState *
       balance_bot_protobuf__robot_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__robot_state__free_unpacked
                     (BalanceBotProtobuf__RobotState *message,
                      ProtobufCAllocator *allocator);
/* BalanceBotProtobuf__Bot2Web methods */
void   balance_bot_protobuf__bot2_web__init
                     (BalanceBotProtobuf__Bot2Web         *message);
size_t balance_bot_protobuf__bot2_web__get_packed_size
                     (const BalanceBotProtobuf__Bot2Web   *message);
size_t balance_bot_protobuf__bot2_web__pack
                     (const BalanceBotProtobuf__Bot2Web   *message,
                      uint8_t             *out);
size_t balance_bot_protobuf__bot2_web__pack_to_buffer
                     (const BalanceBotProtobuf__Bot2Web   *message,
                      ProtobufCBuffer     *buffer);
BalanceBotProtobuf__Bot2Web *
       balance_bot_protobuf__bot2_web__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   balance_bot_protobuf__bot2_web__free_unpacked
                     (BalanceBotProtobuf__Bot2Web *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*BalanceBotProtobuf__PitchPID_Closure)
                 (const BalanceBotProtobuf__PitchPID *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__PitchPIDState_Closure)
                 (const BalanceBotProtobuf__PitchPIDState *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__PitchController_Closure)
                 (const BalanceBotProtobuf__PitchController *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__PitchControllerState_Closure)
                 (const BalanceBotProtobuf__PitchControllerState *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__YawPID_Closure)
                 (const BalanceBotProtobuf__YawPID *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__YawPIDState_Closure)
                 (const BalanceBotProtobuf__YawPIDState *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__YawController_Closure)
                 (const BalanceBotProtobuf__YawController *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__YawControllerState_Closure)
                 (const BalanceBotProtobuf__YawControllerState *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__PhysicalCharacteristics_Closure)
                 (const BalanceBotProtobuf__PhysicalCharacteristics *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__MotorConfig_Closure)
                 (const BalanceBotProtobuf__MotorConfig *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__Drive_Closure)
                 (const BalanceBotProtobuf__Drive *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__Web2Bot_Closure)
                 (const BalanceBotProtobuf__Web2Bot *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__MotorState_Closure)
                 (const BalanceBotProtobuf__MotorState *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__RobotState_Closure)
                 (const BalanceBotProtobuf__RobotState *message,
                  void *closure_data);
typedef void (*BalanceBotProtobuf__Bot2Web_Closure)
                 (const BalanceBotProtobuf__Bot2Web *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    balance_bot_protobuf__pitch_controller_type__descriptor;
extern const ProtobufCEnumDescriptor    balance_bot_protobuf__yaw_controller_type__descriptor;
extern const ProtobufCEnumDescriptor    balance_bot_protobuf__optional_bool__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_pid__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_pidstate__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_controller__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__pitch_controller_state__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_pid__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_pidstate__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_controller__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__yaw_controller_state__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__physical_characteristics__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__motor_config__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__drive__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__web2_bot__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__motor_state__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__robot_state__descriptor;
extern const ProtobufCMessageDescriptor balance_bot_protobuf__bot2_web__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_balancebot_2eproto__INCLUDED */
